# Generated by Django 4.0.5 on 2022-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='profiles/kids.jpg', null=True, upload_to='profiles/'),
        ),
    ]
