# Generated by Django 4.0.5 on 2022-06-08 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('another_title', models.CharField(blank=True, max_length=200, null=True)),
                ('about_image', models.ImageField(blank=True, default='math.jpg', null=True, upload_to='')),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('line_one', models.CharField(blank=True, max_length=200, null=True)),
                ('line_two', models.CharField(blank=True, max_length=200, null=True)),
                ('line_three', models.CharField(blank=True, max_length=200, null=True)),
                ('line_four', models.CharField(blank=True, max_length=200, null=True)),
                ('line_five', models.CharField(blank=True, max_length=200, null=True)),
                ('line_six', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='math.jpg', null=True, upload_to='')),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_image', models.ImageField(blank=True, default='math.jpg', null=True, upload_to='')),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
