# Generated by Django 4.0.5 on 2022-06-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_about_activities_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Sliders',
        ),
    ]
