# Generated by Django 4.0.5 on 2022-06-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
